### ISSUE TITLE
cloud-init does not support for AWS ec2 instance ipv6 interface

### ISSUE THREAD

**Issue by gauravmittal80** [aws/amazon-ec2-net-utils#35]
As we were testing the same cloud-init binary, we see that IPv6 address that gets assigned to the AWS EC2 instance is not reflecting inside the OS. To make it visible we had to add below 2 entries in the ifcfg-eth0.

echo "DHCPV6C=yes" >> /etc/sysconfig/network-scripts/ifcfg-eth0
echo "IPV6INIT=yes" >> /etc/sysconfig/network-scripts/ifcfg-eth0
systemctl restart network

After that I see the IP is visible in eth0, but since the proper routes are not added its not pingable on the network.

So you see this as a bug in cloud-init. I do not see this issue in Oracle Enterprise Linux 7.X.

Current version of cloud-init is 19.4.

**Comment by nmeyerhans** [comment]
Hi @gauravmittal80. Did you mean to open this issue against cloud-init, by any chance? When amazon-ec2-net-utils generates ifcfg entries, it does add the relevant IPv6 related entries to the ifcfg file, as you can see [in ec2net-functions](https://github.com/aws/amazon-ec2-net-utils/blob/8b7e289b983ae42d8bba6ad48cc5f9437078e210/ec2net-functions#L247-L248).

If cloud-init is the right place for your issue, then I suggest reporting it to your OS vendor, as cloud-init 19.4 is not the currently supported [release](https://github.com/canonical/cloud-init/releases), and any fix would likely need to come via your vendor rather than the cloud-init developers themselves.

If I guessed wrong, and you actually believe this to be an issue with amazon-ec2-net-utils, please feel free to reopen it. If you do, please provide detailed information about the operating system you're running (distribution, version, AMI IDs, etc)
